import type { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';
import { useEffect } from 'react';
import { generateHmac } from '@lib/hmacGenerator';

const Home: NextPage = () => {
  const REQUEST_METHOD = 'POST';
  const DOMAIN = 'https://api-gateway.coupang.com';
  const URL = 'https://korgathershop.herokuapp.com/v2/providers/affiliate_open_api/apis/openapi/v1/deeplink';

  // Replace with your own ACCESS_KEY and SECRET_KEY
  const ACCESS_KEY = '8ffaeca8-2c9d-4e68-a208-2ac6d728fc51';
  const SECRET_KEY = 'e6b0e1c0e5589ff34061c21fc338e3ccd1ba954a';

  const REQUEST = {
    coupangUrls: [
      'https://www.coupang.com/np/search?component=&q=good&channel=user',
      'https://www.coupang.com/np/coupangglobal',
    ],
  };
  const test = async () => {
    const authorization = generateHmac(REQUEST_METHOD, URL, SECRET_KEY, ACCESS_KEY);
    axios.defaults.baseURL = DOMAIN;

    try {
      const response = await axios.request({
        method: REQUEST_METHOD,
        url: URL,
        headers: { Authorization: authorization },
        data: REQUEST,
      });
      console.log(response.data);
    } catch (err) {
      console.log('error');
    }
  };
  test();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      sdas
    </div>
  );
};

export default Home;
