import type { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';
import { useEffect } from 'react';
import { generateHmac } from '@lib/hmacGenerator';
import React from 'react';
import AppLayout from 'src/component/AppLayout';
import { Col, Row } from 'antd';
import styled from 'styled-components';

const Home: NextPage = () => {
  return (
    <React.StrictMode>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <StyledRow gutter={[30, 30]}>
          <StyledCol xs={24} lg={12}>
            <Container></Container>
          </StyledCol>
          <StyledCol xs={24} lg={12}>
            <Container></Container>
          </StyledCol>
          <StyledCol xs={24} lg={12}>
            <Container></Container>
          </StyledCol>
          <StyledCol xs={24} lg={12}>
            <Container></Container>
          </StyledCol>
        </StyledRow>
      </AppLayout>
    </React.StrictMode>
  );
};

export default Home;

const StyledRow = styled(Row)`
  margin-top: 20px;
  width: 100%;
  max-width: 960px;
`;

const StyledCol = styled(Col)``;

const Container = styled.div`
  width: 100%;
  background-color: white;
  height: 400px;
  border-radius: 10px;
`;
